import clsx from "clsx";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "sonner";
import "~/styles/globals.css";
import { Providers } from "./_components/providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full w-full">
      <body
        className={clsx(
          inter.className,
          "flex h-full w-full flex-col bg-neutral-900 text-white",
        )}
      >
        <Toaster richColors />
        <div className="w-full flex-grow overflow-hidden">
          <Providers>{children}</Providers>
        </div>
      </body>
    </html>
  );
}
